components/frontend/src/MetricParameters.js, components/frontend/src/Source.js, components/server/datamodel.json, components/server/server/database/datamodels.py
=> Add some help info about metrics and sources.

components/collector/src/collectors/sonarqube.py, components/server/datamodel.json, components/server/example-reports/example-report-hq.json, components/server/example-reports/example-report-next-action.json, components/server/example-reports/example-report-quality-time.json
=> Add complexity metric.

components/frontend/Dockerfile, components/server/src/serve.py, docker-compose.yml
=> Add LDAP option to make LDAP work in BigBoat.

components/collector/src/collector.py, components/collector/src/util.py, components/collector/tests/unittests/collectors/test_owasp_zap.py, components/collector/tests/unittests/test_util.py, components/server/src/routes/measurement.py
=> Issue 193 compare failed measurements

components/server/src/cors.py, components/server/src/database/datamodels.py, components/server/src/database/measurements.py, components/server/src/database/reports.py, components/server/src/database/sessions.py, components/server/src/routes/auth.py, components/server/src/routes/datamodel.py, components/server/src/routes/measurement.py, components/server/src/routes/report.py, components/server/src/serve.py
=> Issue 189 useless import

components/server/datamodel.json, components/server/tests/unittests/test_datamodel.py
=> Fix datamodel and add unit tests.

components/collector/src/__init__.py, components/collector/src/collector.py, components/collector/tests/unittests/collectors/test_azure_devops.py, components/collector/tests/unittests/collectors/test_collector.py, components/collector/tests/unittests/collectors/test_gitlab.py, components/collector/tests/unittests/collectors/test_hq.py, components/collector/tests/unittests/collectors/test_jacoco.py, components/collector/tests/unittests/collectors/test_jenkins.py, components/collector/tests/unittests/collectors/test_jenkins_test_report.py, components/collector/tests/unittests/collectors/test_jira.py, components/collector/tests/unittests/collectors/test_junit.py, components/collector/tests/unittests/collectors/test_ojaudit.py, components/collector/tests/unittests/collectors/test_owasp_dependency_check.py, components/collector/tests/unittests/collectors/test_owasp_zap.py, components/collector/tests/unittests/collectors/test_random_number.py, components/collector/tests/unittests/collectors/test_sonarqube.py, components/collector/tests/unittests/test_collector.py, components/server/README.md, components/server/datamodel.json, components/server/src/database/datamodels.py, components/server/src/database/measurements.py, components/server/tests/unittests/routes/test_measurement.py, components/server/tests/unittests/test_datamodel.py
=> Issue 201 source freshness with multiple sources

components/collector/src/collectors/jacoco.py, components/collector/src/collectors/jenkins_test_report.py, components/collector/src/collectors/junit.py, components/collector/src/collectors/owasp_dependency_check.py, components/collector/src/collectors/owasp_zap.py, components/collector/src/collectors/sonarqube.py, components/collector/tests/unittests/collectors/test_jacoco.py, components/collector/tests/unittests/collectors/test_jenkins_test_report.py, components/collector/tests/unittests/collectors/test_junit.py, components/collector/tests/unittests/collectors/test_owasp_dependency_check.py, components/collector/tests/unittests/collectors/test_owasp_zap.py, components/collector/tests/unittests/collectors/test_sonarqube.py, components/server/datamodel.json, components/server/example-reports/example-report-hq.json, components/server/example-reports/example-report-next-action.json, components/server/example-reports/example-report-quality-time.json, components/server/example-reports/example-report.json
=> Rename source freshness to source up-to-dateness.

components/collector/src/collectors/owasp_dependency_check.py, components/collector/tests/unittests/collectors/test_owasp_dependency_check.py, components/server/datamodel.json, components/server/src/routes/measurement.py
=> Report dependencies instead of vulnerabilities.

components/frontend/src/Report.js, components/frontend/src/Reports.js
=> Summary tag home screen

components/collector/src/collectors/__init__.py, components/collector/src/collectors/calendar.py, components/collector/tests/unittests/collectors/test_calendar.py, components/frontend/src/SourceParameter.js, components/frontend/src/fields/DateInput.js, components/server/datamodel.json, components/server/example-reports/example-report.json, components/server/src/serve.py
=> Issue 183 metric number of days since date

components/frontend/src/CardDashboard.js, components/frontend/src/MetricSummaryCard.js, components/frontend/src/Report.js, components/frontend/src/Reports.js
=> Issue 223 use tag label on home page

components/frontend/src/Measurement.js, components/frontend/src/MetricSummaryCard.js, components/frontend/src/Reports.js, components/frontend/src/StatusPieChart.js, components/server/src/database/reports.py
=> Ues white for missing data.

components/frontend/src/SourcesUnits.js, components/server/datamodel.json
=> Color units depending on unit attributes like severity.

components/frontend/src/FocusableTab.css, components/frontend/src/FocusableTab.js, components/frontend/src/MeasurementDetails.js, components/frontend/src/SourcesUnits.js
=> Make tabs accept keyboard focus.

components/frontend/src/MeasurementDetails.js
=> Reorder tabs.

components/frontend/src/MeasurementDetails.js, components/frontend/src/SourceUnits.js
=> Use one level of tabs instead of two for measurement details.

.gitignore, components/collector/src/collectors/gitlab.py, components/collector/tests/unittests/collectors/test_gitlab.py, components/server/datamodel.json
=> Add Gitlab as source for up-to-dateness of documents.

components/frontend/src/TrendGraph.js
=> Make Y-axis smaller if the measurement values are small.

components/server/src/routes/auth.py
=> Fix logout.

components/collector/src/collectors/__init__.py, components/collector/src/collectors/trello.py, components/collector/src/collectors/wekan.py, components/collector/tests/unittests/collectors/test_trello.py, components/frontend/src/fields/MultipleChoiceInput.js, components/server/datamodel.json
=> Issue 170 trello

components/frontend/src/Measurement.js, components/frontend/src/MeasurementDetails.js, components/frontend/src/TrendGraph.js
=> Issue 262 graph legend

components/collector/src/collectors/owasp_dependency_check.py, components/collector/tests/unittests/collectors/test_owasp_dependency_check.py
=> Support OWASP dependency check XSD 2.0.

components/frontend/package-lock.json, components/frontend/package.json, components/frontend/src/App.js, components/frontend/src/Reports.js
=> Use history package to manage navigation.

components/frontend/src/MetricParameters.js
=> Show default (near) target when the (near) target is changed.

components/collector/src/collectors/gitlab.py, components/collector/tests/unittests/collectors/test_gitlab.py, components/server/datamodel.json
=> Add inactivity parameter.

components/frontend/src/SourceParameter.js, components/frontend/src/SourceParameters.js, components/frontend/src/fields/DateInput.js, components/frontend/src/fields/Input.js, components/frontend/src/fields/IntegerInput.js, components/frontend/src/fields/MultipleChoiceInput.js, components/frontend/src/fields/StringInput.js, components/frontend/src/fields/TextInput.js, components/server/datamodel.json, components/server/tests/unittests/test_datamodel.py
=> Make input fields red when they are mandatory and empty.

components/collector/src/collectors/sonarqube.py, components/server/datamodel.json
=> Add commented out source code metric.

components/server/datamodel.json, components/server/src/routes/report.py, components/server/tests/unittests/routes/test_report.py, components/server/tests/unittests/test_datamodel.py
=> Issue 320 default source

components/frontend/src/SourceEntities.js, components/frontend/src/SourceEntity.js, components/frontend/src/SourceEntityAttribute.js, components/frontend/src/SourceEntityDetails.js, components/frontend/src/TableRowWithDetails.js
=> Issue 130 sort entities

components/frontend/src/Measurement.js, components/frontend/src/Metric.js, components/frontend/src/SourceStatus.js, components/frontend/src/Subject.js
=> Issue 64 sort metrics

components/collector/src/collector.py
=> Run every 900 seconds instead of every 900 days. Oops.

components/art/cypress/integration/common/init_metric_target_and_debt.js, components/art/cypress/integration/technical_debt/technical_debt.js, components/frontend/src/App.js, components/frontend/src/Report.js, components/frontend/src/Subject.js, components/frontend/src/SubjectTitle.js
=> Clicking on subject in dashboard navigates to subject's metrics.

components/collector/src/collectors/sonarqube.py, components/collector/tests/unittests/collectors/test_sonarqube.py, components/server/datamodel.json
=> Issue 341 suppressed sonarqube issues

components/frontend/src/App.js
=> Reset report date if it's the current date.

components/frontend/src/report/Report.js
=> Show error message when report doesn't exist (anymore).

components/art/cypress/integration/technical_debt.feature, components/frontend/src/metric/Measurement.js
=> Issue 353 icons

components/frontend/src/dashboard/StatusPieChart.js
=> Make inner radius of donut charts depend on the number of metrics.

components/frontend/src/report/Report.js, components/frontend/src/report/Reports.js, components/frontend/src/source/SourceEntity.js, components/frontend/src/subject/Subject.js, components/frontend/src/subject/Subjects.js, components/frontend/src/widgets/Tag.js
=> Allow for filtering metrics by tags.

components/frontend/src/App.js, components/frontend/src/fields/DateInput.js, components/frontend/src/fields/Input.js, components/frontend/src/fields/IntegerInput.js, components/frontend/src/fields/MultipleChoiceInput.js, components/frontend/src/fields/SingleChoiceInput.js, components/frontend/src/fields/StringInput.js, components/frontend/src/fields/TextInput.js, components/frontend/src/header_footer/Menubar.js
=> Issue 361 refresh after add report

components/frontend/src/metric/MetricParameters.js, components/server/src/database/datamodels.py, components/server/src/database/measurements.py, components/server/src/routes/report.py, components/server/tests/unittests/database/test_measurements.py, components/server/tests/unittests/routes/test_report.py
=> Add technical debt end date field.

components/frontend/src/report/Report.js
=> Remove filter by tag when the report no longer contains the tag.

components/frontend/src/App.js, components/frontend/src/header_footer/Menubar.js
=> Don't show search bar on landing page.

components/frontend/src/dashboard/CardDashboard.js, components/frontend/src/dashboard/MetricSummaryCard.js
=> Prevent overlapping cards.

components/art/cypress/integration/common/init_metric_target_and_debt.js, components/art/cypress/integration/technical_debt/technical_debt.js, components/frontend/src/App.js, components/frontend/src/api/report.js, components/frontend/src/report/Report.js, components/frontend/src/report/Reports.js, components/server/src/routes/report.py, components/server/tests/unittests/routes/test_report.py
=> Issue 220 tag reports

.gitignore, components/collector/requirements.txt, components/collector/setup.cfg, components/collector/src/collectors/__init__.py, components/collector/src/collectors/performancetest_runner.py, components/collector/tests/unittests/collectors/test_performancetest_runner.py, components/server/datamodel.json, components/server/example-reports/example-report.json, components/server/requirements.txt, components/testdata/performancetest-runner-loadtestreport.html
=> Add performance metrics.

components/frontend/Dockerfile, components/frontend/src/App.js, docker-compose.yml
=> Issue 406 use window location to derive server url

.gitignore, CHANGELOG.md, components/frontend/.env
=> Fix missing version number in frontend.

components/art/cypress/integration/technical_debt/technical_debt.js, components/frontend/src/App.js, components/frontend/src/dashboard/CardDashboard.js, components/frontend/src/fields/MultipleChoiceInput.js, components/frontend/src/fields/SingleChoiceInput.js, components/frontend/src/fields/StringInput.js, components/frontend/src/report/Report.js, components/frontend/src/source/Sources.js
=> Fix SonarQube issues.

CHANGELOG.md, components/frontend/src/metric/TrendGraph.js
=> Trend graphs would be too tall and overlap with the next metric.

CHANGELOG.md, components/frontend/src/App.js, components/frontend/src/metric/TrendGraph.js, components/frontend/src/report/Report.js, components/frontend/src/report/Reports.js, components/server/src/database/datamodels.py, components/server/src/database/reports.py, components/server/tests/unittests/routes/test_datamodel.py
=> Issue 416 time travel

CHANGELOG.md, components/frontend/src/header_footer/Menubar.js
=> Fix calendar popup location.

components/frontend/src/App.js, components/server/src/routes/measurement.py, components/server/src/serve.py
=> Connect to event source when user opens a report directly or refreshes the report

components/collector/src/collectors/performancetest_runner.py, components/collector/tests/unittests/collectors/test_performancetest_runner.py, components/frontend/src/fields/IntegerInput.test.js, components/frontend/src/metric/MetricParameters.js, components/server/datamodel.json, docs/CHANGELOG.md
=> Add performancetest stability metric.

components/collector/src/collectors/performancetest_runner.py, components/collector/tests/unittests/collectors/test_collector.py, components/collector/tests/unittests/collectors/test_performancetest_runner.py, components/server/datamodel.json, docs/CHANGELOG.md
=> Add performance scalability metric.

components/server/example-reports/example-report.json, docs/CHANGELOG.md
=> Add performance test stability and scalability metrics to the example report

components/collector/src/collector.py, components/collector/src/collectors/__init__.py, components/collector/src/collectors/manual_number.py, components/collector/tests/unittests/collectors/test_manual_number.py, components/frontend/src/metric/MeasurementDetails.js, components/frontend/src/metric/SourceStatus.js, components/frontend/src/source/Source.js, components/frontend/src/source/SourceParameters.js, components/frontend/src/source/Sources.js, components/server/datamodel.json, components/server/src/initialization/bottle.py
=> Add manual number source.

components/collector/src/metric_collector.py, components/collector/tests/unittests/test_metrics_collector.py, docs/CHANGELOG.md
=> Issue 475 issues jira

components/collector/src/source_collectors/trello.py, components/collector/src/source_collectors/wekan.py, components/collector/tests/unittests/source_collectors/test_trello.py, components/collector/tests/unittests/source_collectors/test_wekan.py, components/server/src/data/datamodel.json
=> Issue 472 ignore lists for source up to dateness

components/collector/src/source_collectors/jira.py, components/collector/tests/unittests/source_collectors/test_jira.py, components/server/src/data/datamodel.json, docs/CHANGELOG.md
=> Issue 481 manual test case duration

components/frontend/src/api/report.js, components/frontend/src/changelog/ChangeLog.js, components/frontend/src/header_footer/Menubar.js, components/frontend/src/metric/MeasurementDetails.js, components/frontend/src/report/ChangeLog.js, components/frontend/src/report/ReportTitle.js, components/frontend/src/source/Source.js, components/frontend/src/subject/Subject.js, components/frontend/src/subject/SubjectTitle.js, components/server/src/database/measurements.py, components/server/src/database/reports.py, components/server/src/database/sessions.py, components/server/src/initialization/bottle.py, components/server/src/routes/changelog.py, components/server/src/routes/measurement.py, components/server/src/routes/report.py, components/server/tests/unittests/routes/test_changelog.py, components/server/tests/unittests/routes/test_measurement.py, components/server/tests/unittests/routes/test_report.py, docs/CHANGELOG.md
=> Issue 285 activity log

components/server/src/routes/report.py, components/server/tests/unittests/routes/test_report.py
=> Don't show passwords in change log.

components/collector/src/source_collectors/azure_devops.py, docs/CHANGELOG.md
=> Don't try to retrieve more work items from Azure DevOps than allowed

components/frontend/src/fields/StringInput.js, docs/CHANGELOG.md
=> Users can now select a suggestion and edit it in input fields with suggestions

components/ldap/.dockerignore, components/ldap/Dockerfile, components/ldap/bootstrap/ldif/jane.ldif, components/ldap/bootstrap/ldif/john.ldif, components/server/src/routes/auth.py, components/server/src/utilities/ldap.py, components/server/tests/unittests/routes/test_auth.py, docker/ci.env, docker/dev.env, docker/docker-compose.ci.yml, docker/docker-compose.override.yml, docker/production.env, docker/staging.env, docs/CHANGELOG.md, docs/DEPLOY.md, docs/DEVELOP.md, docs/USAGE.md
=> Add ability to login with LDAP-uid.

components/frontend/src/source/SourceEntityAttribute.js, docs/CHANGELOG.md
=> Issue 452 row height

components/collector/src/source_collectors/__init__.py, components/collector/src/source_collectors/owasp_zap.py, components/collector/src/source_collectors/quality_time.py, components/collector/src/source_collectors/source_collector.py, components/collector/tests/unittests/source_collectors_tests/test_quality_time.py, components/server/src/data/datamodel.json, components/server/src/routes/auth.py, components/server/src/utilities/ldap.py, docs/CHANGELOG.md
=> Issue 337 quality time as source

components/collector/src/source_collectors/jenkins_test_report.py, components/collector/src/source_collectors/junit.py, components/collector/src/source_collectors/performancetest_runner.py, components/collector/src/source_collectors/robot_framework.py, components/collector/tests/unittests/source_collectors_tests/test_collector.py, components/collector/tests/unittests/source_collectors_tests/test_jenkins_test_report.py, components/collector/tests/unittests/source_collectors_tests/test_junit.py, components/collector/tests/unittests/source_collectors_tests/test_robot_framework.py, components/frontend/src/metric/Measurement.js, components/frontend/src/metric/MetricParameters.js, components/frontend/src/source/SourceEntityAttribute.js, components/server/src/data/datamodel.json, components/server/src/database/datamodels.py, components/server/src/database/measurements.py, components/server/src/routes/report.py, components/server/tests/unittests/data/test_datamodel.py, docs/CHANGELOG.md
=> Issue 552 configurable metric direction

components/frontend/src/metric/Measurement.js, components/frontend/src/metric/MeasurementDetails.js, components/frontend/src/metric/Metric.js, components/frontend/src/subject/Subject.js, components/server/src/routes/report.py, components/server/tests/unittests/routes/test_report.py, docs/CHANGELOG.md, docs/USAGE.md
=> Issue 585 reorder metrics

components/collector/src/source_collectors/cxsast.py, components/collector/tests/unittests/source_collectors_tests/source_collector_test_case.py, docs/CHANGELOG.md
=> Bug 468 checkmarx collector fails

components/server/src/data/datamodel.json
=> Add Azure DevOps as source for the unmerged branches metric.

components/collector/src/source_collectors/azure_devops.py, components/collector/src/source_collectors/gitlab.py, components/collector/src/source_collectors/quality_time.py, components/collector/src/source_collectors/source_collector.py, components/collector/tests/unittests/source_collectors_tests/test_azure_devops.py, components/server/src/data/datamodel.json, docs/CHANGELOG.md
=> Add Azure DevOps as source for the 'Source up-to-dateness' metric

components/collector/src/metric_collectors/metric_collector.py, components/collector/src/source_collectors/source_collector.py, components/collector/tests/unittests/metric_collectors_tests/test_metrics_collector.py, docs/CHANGELOG.md
=> Issue 652 jenkins 401

components/collector/src/source_collectors/sonarqube.py, components/collector/src/source_collectors/source_collector.py, components/collector/tests/unittests/source_collectors_tests/test_azure_devops.py, components/collector/tests/unittests/source_collectors_tests/test_sonarqube.py, components/frontend/src/source/SourceParameter.js, components/frontend/src/source/SourceParameter.test.js, components/frontend/src/source/SourceParameters.js, components/frontend/src/source/SourceParameters.test.js, components/server/src/data/datamodel.json, components/server/tests/unittests/data/test_datamodel.py, docs/CHANGELOG.md
That means the "Size (Non-commented LOC)" metric is now deprecated. Closes #644.
=> The "Size (LOC)" metric can now either count all lines of code or all non-commented lines of code
